name: mongo-sharding
services:
  # ============================================
  # CONFIG SERVER (single instance)
  # ============================================
  configSrv:
    container_name: configSrv
    image: dh-mirror.gitverse.ru/mongo:latest
    restart: always
    ports:
      - "27017:27017"
    networks:
      app-network:
        ipv4_address: 173.17.0.10
    volumes:
      - configSrv_data:/data/db
    command:
      [
        "--configsvr",
        "--replSet",
        "config_server",
        "--bind_ip_all",
        "--port",
        "27017"
      ]
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      start_period: 10s

  # ============================================
  # SHARD 1 (single instance)
  # ============================================
  mongo-shard1:
    container_name: mongo-shard1
    image: dh-mirror.gitverse.ru/mongo:latest
    restart: always
    ports:
      - "27018:27018"
    networks:
      app-network:
        ipv4_address: 173.17.0.20
    volumes:
      - mongo-shard1_data:/data/db
    command:
      [
        "--shardsvr",
        "--replSet",
        "shard1",
        "--bind_ip_all",
        "--port",
        "27018"
      ]
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      start_period: 10s

  # ============================================
  # SHARD 2 (single instance)
  # ============================================
  mongo-shard2:
    container_name: mongo-shard2
    image: dh-mirror.gitverse.ru/mongo:latest
    restart: always
    ports:
      - "27019:27019"
    networks:
      app-network:
        ipv4_address: 173.17.0.30
    volumes:
      - mongo-shard2_data:/data/db
    command:
      [
        "--shardsvr",
        "--replSet",
        "shard2",
        "--bind_ip_all",
        "--port",
        "27019"
      ]
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      start_period: 10s

  # ============================================
  # MONGOS ROUTER (single instance)
  # ============================================
  mongos_router:
    container_name: mongos_router
    image: dh-mirror.gitverse.ru/mongo:latest
    restart: always
    ports:
      - "27020:27020"
    networks:
      app-network:
        ipv4_address: 173.17.0.40
    command:
      [
        "mongos",
        "--configdb",
        "config_server/configSrv:27017",
        "--bind_ip_all",
        "--port",
        "27020"
      ]
    depends_on:
      - configSrv
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      start_period: 10s

  # ============================================
  # API (single instance)
  # ============================================
  pymongo-api:
    container_name: pymongo-api
    build:
      context: api_app
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    networks:
      app-network:
        ipv4_address: 173.17.0.60
    environment:
      MONGODB_URL: "mongodb://mongos_router:27020"
      MONGODB_DATABASE_NAME: "somedb"
    depends_on:
      - mongos_router
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 5s
      start_period: 10s

networks:
  app-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 173.17.0.0/16

volumes:
  configSrv_data:
  mongo-shard1_data:
  mongo-shard2_data:
